const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEMS: "ADD_ITEMS",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
};

export default CartActionTypes;
